# Generated by Django 4.2.2 on 2023-06-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aisles",
            fields=[
                ("aisle_id", models.IntegerField(primary_key=True, serialize=False)),
                ("aisle", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "department_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("department", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("eval_set", models.CharField(max_length=255)),
                ("order_number", models.IntegerField()),
                ("order_dow", models.IntegerField(blank=True, null=True)),
                ("order_hour_of_day", models.IntegerField(blank=True, null=True)),
                ("days_since_prior_order", models.IntegerField(blank=True, null=True)),
                (
                    "total_price_usd",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "aisle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app2.aisles",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app2.departments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_to_cart_order", models.IntegerField(blank=True, null=True)),
                ("reordered", models.BooleanField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app2.orders",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app2.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("last_updated", models.DateTimeField()),
                (
                    "aisle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app2.aisles",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app2.departments",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce_app2.products",
                    ),
                ),
            ],
        ),
    ]
