# Generated by Django 4.2.2 on 2023-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="days_since_prior_order",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
