# Generated by Django 4.2.2 on 2023-06-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_app2", "0002_alter_orders_days_since_prior_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("product", "aisle", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="orderproducts",
            unique_together={("order", "product")},
        ),
    ]
